# roles/mythtv-pacman/tasks/main.yml

- name: create a list of essential system utils
  set_fact:
    pacman_pkg_lst:
      - lsb-release
      - cronie

- name: add compilers and build essentials
  set_fact:
    pacman_pkg_lst:
      - '{{ pacman_pkg_lst }}'
      - base-devel
      - nasm
      - ccache
      - git

- name: add mythtv essential build libraries
  set_fact:
    pacman_pkg_lst:
      - '{{ pacman_pkg_lst }}'
      - lame
      - libbluray
      - libxnvctrl
      - libsamplerate
      - libxv
      - libxinerama
      - libxrandr
      - libxml2
      - taglib
      - exiv2
      - libzip
      - soundtouch

- name: add mythtv optional build libraries
  set_fact:
    pacman_pkg_lst:
      - '{{ pacman_pkg_lst }}'
      - libcec
      - libass
      # AUR only - libhdhomerun
      - libvdpau
      - libva
      - x264
      - x265
      - libvpx
      - dav1d
      - xvidcore
      - pulseaudio
      - libavc1394
      - libiec61883
      - lirc

- name: add mythtv essential python modules
  set_fact:
    pacman_pkg_lst:
      - '{{ pacman_pkg_lst }}'
      - python-lxml
      # AUR only - urlgrabber
      - python-mysqlclient
      - python-requests
      - python-simplejson
      - python-future
      - python-setuptools

- name: add mythtv essential perl modules
  set_fact:
    pacman_pkg_lst:
      - '{{ pacman_pkg_lst }}'
      - perl-dbi
      - perl-dbd-mysql
      # AUR only - perl-net-upnp
      - perl-io-socket-inet6
      - perl-date-manip
      - perl-xml-simple
      - perl-xml-xpath
      - perl-image-size
      - perl-datetime-format-iso8601
      - perl-soap-lite
      - perl-json

- name: add mythtv essential plugin libraries
  set_fact:
    pacman_pkg_lst:
      - '{{ pacman_pkg_lst }}'
      - flac
      - libcdio
      - libcdio-paranoia
      - libmariadbclient
      - python-pycurl
      - python-oauthlib

- name: final package list
  debug:
    msg:
      '{{ lookup("flattened", pacman_pkg_lst) }}'

- name: install packages
  pacman:
    name:
      '{{ lookup("flattened", pacman_pkg_lst ) }}'
    state:
      present

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
