# roles/mythtv-pacman/tasks/main.yml

- name: install essential system utils
  pacman: name={{ item }} state=installed
  with_items:
    - lsb-release
    - cronie

- name: install compilers and build essentials
  pacman: name={{ item }} state=installed
  with_items:
    - base-devel
    - yasm
    - ccache

- name: install mythtv essential build libraries
  pacman: name={{ item }} state=installed
  with_items:
    - lame
    - libxv
    - libxinerama
    - libxrandr
    - libxml2
    - exiv2

- name: install mythtv essential python modules
  pacman:  name={{ item }} state=installed
  with_items:
    - python2-lxml
    - urlgrabber
    - python2-oauth
    - mysql-python

- name: install mythtv essential perl modules
  pacman:  name={{ item }} state=installed
  with_items:
    - perl-dbi
    - perl-dbd-mysql
    - perl-net-upnp
    - perl-io-socket-inet6
    - perl-date-manip
    - perl-xml-simple
    - perl-xml-xpath
    - perl-image-size
    - perl-datetime-format-iso8601
    - perl-soap-lite
    - perl-json

- name: install mythtv essential plugin libraries
  pacman:  name={{ item }} state=installed
  with_items:
    - flac
#    - libtag1-dev
#    - libcdio-dev
#    - libcdio-paranoia-dev
    - libmariadbclient
