---

- name: install qt5 libraries
  pacman:
    name:
      - qt5-base
      - qt5-script
      - qt5-webkit
    state:
      present
  tags:
    - qt5

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
