# Install Qt5

---

- name: create a list of dnf qt5 libraries
  set_fact:
    dnf_pkg_lst:
      - qt5-qtbase-devel
      - qt5-qtwebkit-devel
      - qt5-qtscript-devel
      # packages in repo for fedora, and in epel for centos7/rhel7
      # - none yet
  tags:
    - qt5

# This looks like overkill, but the intent is to provide future maintainers
# with a template to add more (especially conditional) packages.

- name: add qt5 runtime dependencies
  set_fact:
    dnf_pkg_lst:
      - '{{ dnf_pkg_lst }}'
      - qt5-qtbase-mysql
  tags:
    - qt5

- name: final dnf qt5 package list
  debug:
    msg:
      '{{ lookup("flattened", dnf_pkg_lst) }}'
  tags:
    - qt5

- name: install dnf qt5 packages
  dnf:
    name:
      '{{ lookup("flattened", dnf_pkg_lst ) }}'
    state: present
  tags:
    - qt5

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
