---

- name: install essential libraries
  pkgng:
    name:
      - qt5
    state:
      present
  tags:
    - qt5

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=2:
