# roles/perl/tasks/cpanm_install.yml
#
# install perl modules with ansible's cpanm capabiltiy
#
# Alternative mirrors that occasionally fail:
# --mirror 'http://cpan.cpantesters.org/'
# --mirror 'https://metacpan.org/'
---

- name: 'cpanm_install | Install perl modules'
  become: false
  command: cpanm
    --force
    {{ perl_modules | join(' ') }}
  ignore_errors: yes
  environment:
    OPENSSL_PREFIX: '{{ openssl_path }}'
...

# vim: set expandtab tabstop=2 shiftwidth=2 smartindent noautoindent colorcolumn=3:
