# v14

---

packages:
  - avahi-libdns
  - autoconf-2.72p0
  - automake-1.18
  - ccache
  - cmake
  - exiv2
  - fftw
  - flac
  - gcc-11.2.0p19
  - git
  - glslang
  - gmake
  - gnutls
  - gperf
  - hdhomerun
  - jack
  - lame
  - libass
  - libbluray
  - libcdio
  - libmpeg2
  - libsamplerate
  - libtool
  - libv4l
  - libvorbis
  - libvpx
  - libxml
  - libzip
  - lzo
  - meson
  - minizip
  - nasm
  - ninja
  - openssl-3.6.0p0v0
  - p5-DBD-mysql
  - p5-DBI
  - p5-DateManip
  - p5-DateTime-Format-ISO8601
  - p5-IO-Socket-INET6
  - p5-Image-Size
  - p5-JSON
  - p5-Net-UPnP
  - p5-SOAP-Lite
  - p5-XML-Simple
  - p5-XML-XPath
  - p5-libwww
  - php-8.4.15p0
  - pulseaudio
  - py3-lxml
  - py3-mysqlclient
  - py3-oauthlib
  - py3-pip
  - py3-pymysql
  - py3-requests
  - py3-setuptools
  - py3-simplejson
  - py3-urlgrabber
  - python-3.12.11
  - sdl2
  - soundtouch
  - sqlite3
  - subversion
  - taglib
  - vulkan-headers
  - vulkan-loader
  - x264
  - x265
  - xvidcore

qt6_packages:
  - qt6-qtbase
  - qt6-mysql
  - qt6-qtconnectivity
  - qt6-qtdeclarative
  - qt6-qtimageformats
  - qt6-qtmultimedia
  - qt6-qtnetworkauth
  - qt6-qttools
  - qt6-qtwebchannel
  - qt6-qtwebengine
  - qt6-qtwebsockets
  - qt6-qtwebview

...
